Cargo.toml

Avoids https://github.com/rust-lang/rust/issues/75045, which you would otherwise hit when using the nRF HAL.

Avoid opt-level=z

---

Cargo.toml

This works around https://github.com/rust-lang/cargo/issues/3244, which would otherwise cause rebuilds of the entire crate graph for no reason.

Don't enable LTO in the dev profile

---

Cargo.toml
src/lib.rs

panic-probe is needed for on-device integration tests, and would conflict with the hand-rolled panic handler that is currently present.

Use panic-probe instead of a custom panic handler

---

Cargo.toml
testsuite/Cargo.toml
testsuite/tests/test.rs

This adds a package with integration tests that will run on the device. This can be done via `cargo test -p testsuite` or by clicking rust-analyzer's "Run" button on the test. Any panic will fail the test, as you would expect.

Add an on-device test suite

---

cargo-generate.toml

Otherwise this gets put into every repo created from this, which probably isn't the nicest thing to do

Exclude funding info from template

---

cargo-generate.toml

A recent commit [8b9e0f5 ](https://github.com/knurling-rs/app-template/commit/8b9e0f5ec089bf980d53a44f0dfbc0edf9326390)has broken `cargo generate` due to introducing the text `{{chip}}` in `README.md` which is being mistaken for Liquid template syntax by `cargo generate`. As `README.md` never needs to have its content processed by `cargo generate`, excluding it seems appropriate.
```
cargo generate --git https://github.com/knurling-rs/app-template --branch main --name knurling-co2
Creating project called `knurling-co2`...
Error:  Error replacing placeholders `C:\rust\knurling-co2\README.md`
Caused by:
liquid: Unknown variable
with:
requested variable=chip
available variables=authors, crate_name, project-name
```

Added README.md to cargo-generate.toml excludes

---

README.md

Here is a suggested addition to the readme to clarify the need for a `memory.x`

Fix #19 - add step for memory.x

---

Cargo.toml

I believe Cargo now does this by default

Remove proc macro opt-level override

---

Cargo.toml
README.md
testsuite/Cargo.toml

also enable panic-probe's 'print-defmt' so panic messages are printed
~~blocked on crates.io release~~

use crates.io versions

---

.cargo/config.toml

rationale is in https://github.com/rust-embedded/cortex-m-quickstart/pull/95
we want to avoid potentially running into that issue in the future

pass --nmagic to the linker

---

Cargo.toml
README.md
testsuite/Cargo.toml
testsuite/tests/test.rs

must be merged after `defmt-test` has been published on crates.io

use defmt-test in the test suite

---

Cargo.toml
src/bin/panic.rs
src/lib.rs
testsuite/tests/test.rs

switch test-suite from core::assert to defmt assertions which sport color diffs
it also adds a defmt::panic_handler to avoid the panic message being printed twice on defmt::panic (as documented in the defmt book)
this PR is blocked on the release of defmt v0.1.2

use defmt::assert; add defmt::panic_hnadler

---

.cargo/config.toml

This now gets automatically detected

Remove `--defmt` flag from probe-run

---

testsuite/tests/test.rs

The imports were unused, the libcore macros were still in use. Qualify them as `defmt::assert*` instead.

Actually use the defmt assertion macros

---

Cargo.toml

Cargo doc says:
> Note that when using the cargo test and cargo bench commands, the test/bench profiles only apply to the final test executable. Dependencies will continue to use the dev/release profiles.
So with the current settings, `cargo test` optimizes all dependencies but not the top level
crate (e.g. `test/foo.rs`)
This commit adds optimizations to the last `rustc` invocation of `cargo test`. This results in a 6%
reduction in binary size when doing `cargo test` on our sample test file.

also enable optimizations in the `test` profile

---

Cargo.toml

executable build with `cargo test --release` are built with the `bench` profile. By default, this profile is similar to the default `release` profile so it has `debug = 0`. The result is that `cargo test --release` results in (1) log messages having no location information and (2) knurling-rs/probe-run#9, which makes the process exit with nonzero exit code even when all test fails.
this PR overrides the `bench` profile to match the `release` profile override. This fixes above issues.

add debuginfo to `test --release`

---

README.md

This PR documents the `rust-analyzer.linkedProjects` config for VS code, as suggested by https://github.com/knurling-rs/defmt/pull/395.

`README.md`: Document `rust-analyzer.linkedProjects`

---

testsuite/Cargo.toml
testsuite/src/lib.rs

Without this change, if `testsuite/src/lib.rs` will be crated and `cargo
test` is invoked, cargo will try to link libtest with the crate.
As this crate is `no_std` and will usually be run for targets, where no
std library exists and therefor also no libtest, this will fail with an
error similar to this:
error[E0463]: can't find crate for `test`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: could not compile `testsuite`
To circumvent this issue, disable the harness for lib as well.

Disable test harness for lib target

---

README.md

Ran into the following conflict:
This update solves it.

Updates nrf-hal version to 0.14.0 to resolve dependency conflicts.

---

Cargo.toml

to work around rustc issue 90357

disable LTO

---

Cargo.toml

`lto = 'false'` breaks build on the current nightly. It has to be `lto = false`, without the `'`.
```console
$ cargo build --bins
Compiling krate v0.1.0 (/home/urhengulas/Documents/github.com/knurling-rs/krate)
Finished dev [optimized + debuginfo] target(s) in 0.16s
$ cargo +nightly build --bins
error: failed to parse manifest at `/home/urhengulas/Documents/github.com/knurling-rs/krate/Cargo.toml`
Caused by:
`lto` setting of string `"false"` for `bench` profile is not a valid setting, must be a boolean (`true`/`false`) or a string (`"thin"`/`"fat"`/`"off"`) or omitted.
```
Raised in https://github.com/knurling-rs/app-template/pull/61#issuecomment-1166687101.

Fix `lto` option in cargo profile

---

Cargo.toml
src/lib.rs

Instead of a plain breakpoint, try and give the debugger some idea of why we stopped.
Supported by QEMU, patching being added to probe-rs and ignored by probe-run.

Use semihosting to exit the test program.

---

Cargo.toml

Rust edition = "2024"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

Update dependencies and rust edition
